// /*
//  * This Java source file was generated by the Gradle 'init' task.
//  */
// package testing.aasaan;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         App classUnderTest = new App();
//         System.out.println("User is navigated to Cart Page successfully");
//         assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
//     }
// }
